Update requirements, fixes pipeline issues
Updates ansible-core to current version 2.20.3

Update requirements by recompiling with:
```
pip-compile requirements.in
pip-compile requirements-dev.in
```
Using python 3.14

Fixes the error:
```
Update requirement to fix docker.errors.DockerException

docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
```
Caused by an outdated requests version.